In [1]:
import astropy.io.fits as fits
import astropy.units as u
from astropy.coordinates import SkyCoord
import numpy as np
import os
import pandas as pd
import glob

from create_figs import create_m0_map, mark_sources, plot_vector, plot_dotted_vector

import warnings
warnings.filterwarnings("ignore")

In [2]:
# helper function to extract channel indices from the data table
def getIdx(listOf):
    ranges = []
    
    for string in listOf:
        if pd.isna(string):  # Skip NaN values
            continue
        
        for part in string.split(', '):
            if '-' in part:  # Handle ranges
                start, end = map(int, part.split('-'))
                ranges.append(np.r_[start:end + 1])  # Use np.r_
            else:  # Handle single values
                ranges.append(int(part))  # Append as integer
    
    # Ensure `ranges` is not empty before passing to np.r_
    if not ranges:
        return np.r_[:]  # Returns an empty np.r_

    return np.r_[tuple(ranges)]  # Use `tuple(ranges)` to avoid errors

In [3]:
# read data
source_info = pd.read_csv("../data/output/source_info.csv")
source_info['Main'] = source_info['Main'].apply(lambda x: str(x).casefold())
source_info.set_index('Main', inplace=True)

df = pd.read_csv('../data/output/outflow_data.csv')
df

,group,field,source_a,source_a_ra,source_a_dec,source_b,source_b_ra,source_b_dec,distance,outflow_source,red_channels,blue_channels,red_outflow_PA,blue_outflow_PA,outflow_PA,binary_PA,delta_PA
0,orion,HOPS-12,B-A,83.787271,-5.931953,B-B,83.787312,-5.931911,388.6,B-A,92-97,103-107,158.050,156.195,157.1225,45.000000,67.877500
1,orion,HOPS-12,A,83.785962,-5.931844,NaN,NaN,NaN,388.6,A,92-97,NaN,156.980,NaN,156.9800,NaN,NaN
2,orion,HOPS-290,A,84.989071,-7.492528,B,84.988871,-7.492419,405.5,A,91-94,99-102,291.515,295.520,293.5175,298.442929,4.925429
3,orion,HOPS-290,A,84.989071,-7.492528,B,84.988871,-7.492419,405.5,B,91-95,NaN,227.590,230.185,228.8875,298.442929,69.555429
4,orion,HOPS-92,A-A,83.826404,-5.009150,A-B,83.826367,-5.009217,392.7,both,NaN,106-112,NaN,76.030,76.0300,209.357754,46.672246
5,orion,HOPS-92,B,83.826125,-5.009422,NaN,NaN,NaN,392.7,B,93-97,NaN,268.760,NaN,268.7600,NaN,NaN
6,orion,HOPS-288,A-A,84.983338,-7.507658,A-B,84.983358,-7.507694,405.5,both,85-91,NaN,56.370,NaN,56.3700,150.018361,86.351639
7,orion,HOPS-288,B,84.983471,-7.507767,NaN,NaN,NaN,405.5,B,NaN,102-108,NaN,211.770,211.7700,NaN,NaN
8,orion,HOPS-203,A,84.095271,-6.768508,B,84.095258,-6.768542,383.5,both,96-100,NaN,143.810,NaN,143.8100,200.556045,56.746045
9,orion,HOPS-203,C,84.095408,-6.769297,NaN,NaN,NaN,383.5,C,96-100,NaN,100.920,NaN,100.9200,NaN,NaN
10,orion,HH270VLA1,A,87.894113,2.946114,B,87.894167,2.946078,430.1,both,94-100,104-109,49.765,50.320,50.0425,123.690068,73.647568
11,orion,HOPS-32,A,83.647725,-5.666481,B,83.647633,-5.666550,390.6,B,95-98,102-106,156.855,161.235,159.0450,232.853313,73.808313
12,orion,HOPS-84,A,83.860667,-5.065311,B,83.860571,-5.065481,392.8,both,98-100,"104, 106-107",84.235,81.395,82.8150,209.491362,53.323638
13,orion,HOPS-168,A,84.078921,-6.756550,B,84.078967,-6.756522,383.3,both,91-98,104-115,161.630,157.070,159.3500,58.781597,79.431597
14,orion,HOPS-281,A,85.102700,-7.718931,B,85.102500,-7.718992,416.1,A,91-94,99-105,24.675,27.365,26.0200,253.009177,46.989177
15,orion,HOPS-312,A,85.773708,-1.265164,B,85.773771,-1.265231,416.3,both,88-91,97-98,216.980,215.765,216.3725,136.847610,79.524890
16,orion,HOPS-364,A,86.902346,0.334978,B,86.902308,0.335000,427.8,both,94-98,105-108,285.060,267.545,276.3025,300.650668,24.348168
17,orion,HOPS-395,A,84.821217,-7.406819,B,84.821171,-7.406825,397.2,B,94-95,98,181.000,167.335,174.1675,263.088773,88.921273
18,orion,HOPS-400,A,85.688525,-1.270450,B,85.688571,-1.270564,415.4,A,95-98,103-108,276.240,257.050,266.6450,158.078221,71.433221
19,orion,HOPS-182,A,84.078312,-6.369503,B,84.078229,-6.369764,385.1,both,88-93,104-107,242.645,226.640,234.6425,197.700428,36.942072
20,orion,HOPS-323,A,86.698737,0.007019,B,86.698612,0.006892,428.4,both,94-99,105-107,299.430,306.750,303.0900,224.370401,78.719599
21,orion,HOPS-282,A,85.108713,-7.625578,B,85.108667,-7.625583,414.7,both,93-95,99-101,185.045,180.915,182.9800,263.088773,80.108773
22,orion,HOPS-366,A,86.766679,0.369536,B,86.766704,0.369569,430.5,both,80-87,112-120,136.620,NaN,136.6200,36.869898,80.249898
23,orion,HOPS-193,A,84.126175,-6.021419,B,84.126179,-6.021492,387.8,both,97-99,104,89.440,97.845,93.6425,176.698134,83.055634
24,orion,HOPS-304,A,85.441475,-1.940719,B,85.441300,-1.940778,409.5,both,94-98,107-109,316.465,346.705,331.5850,251.565051,80.019949
25,orion,HOPS-361-N,C-A,86.769296,0.363292,C-B,86.769271,0.363300,430.4,both,81-88,NaN,200.955,NaN,200.9550,288.434949,87.479949
26,orion,HOPS-384,A,85.433896,-1.912794,A-B,85.433917,-1.912769,409.5,both,NaN,108-112,NaN,184.370,184.3700,39.805571,35.435571
27,orion,HOPS-363,A,86.679675,0.014542,B,86.679717,0.014514,428.4,both,92-93,107-109,80.665,104.955,92.8100,123.690068,30.880068
28,orion,HOPS-173,A,84.108504,-6.418081,B,84.108546,-6.418142,384.9,both,NaN,102,NaN,246.990,246.9900,145.713123,78.723123
29,orion,HOPS-75,A,83.861167,-5.102919,B,83.861158,-5.102989,392.8,both,100-101,106-107,93.385,99.670,96.5275,186.842773,89.684727
30,orion,HOPS-213,A,85.700367,-8.669019,B,85.700321,-8.668967,435.6,B,92-93,97-98,262.230,266.745,264.4875,319.028264,54.540764
31,perseus,Per-emb-2,A,53.074729,30.829897,B,53.074717,30.829917,300.0,B,146-150,158-163,305.285,307.060,306.1725,327.264774,21.092274
32,perseus,Per-emb-5,A,52.837258,30.758386,B,52.837258,30.758386,300.0,both,141-148,164-173,297.655,298.945,298.3000,90.000000,28.300000
33,perseus,Per-emb-12,A,52.293875,31.225275,B,52.293458,31.225597,300.0,B,140-147,159-164,31.110,25.165,28.1375,307.715976,80.421524
34,perseus,Per-emb-12,A,52.293875,31.225275,B,52.293458,31.225597,300.0,A,140-147,159-164,-9.120,9.815,0.3475,307.715976,52.631524
35,perseus,Per-emb-17,A,51.912917,30.217522,B,51.912958,30.217458,300.0,both,144-148,156-162,63.650,47.650,55.6500,146.888658,88.761342
36,perseus,Per-emb-18,A,52.296946,31.308608,B,52.296917,31.308603,300.0,both,NaN,160-165,NaN,346.545,346.5450,259.215702,87.329298
37,perseus,Per-emb-22,A,51.343333,30.753669,B,51.343125,30.753650,300.0,B,138-144,155-170,125.660,134.160,129.9100,264.667841,45.242159
38,perseus,Per-emb-22,A,51.343333,30.753669,B,51.343125,30.753650,300.0,A,138-145,155-171,134.905,134.295,134.6000,264.667841,49.932159
39,perseus,Per-emb-27,A,52.231542,31.243597,B,52.231500,31.243439,300.0,A,142-148,161-165,34.600,10.880,22.7400,194.743563,7.996437
40,perseus,Per-emb-27,A,52.231542,31.243597,B,52.231500,31.243439,300.0,B,142-149,161-166,NaN,113.920,113.9200,194.743563,80.823563
41,perseus,Per-emb-33,A,51.401333,30.754122,B,51.401292,30.754192,300.0,both,NaN,154-164,NaN,123.270,123.2700,329.036243,25.766243
42,perseus,Per-emb-33,C,51.401583,30.754067,NaN,NaN,NaN,300.0,C,NaN,154-165,NaN,107.655,107.6550,NaN,NaN
43,perseus,Per-emb-35,A,52.154542,31.225206,B,52.155083,31.225472,300.0,B,NaN,159-163,NaN,307.715,307.7150,63.788622,63.926378
44,perseus,Per-emb-35,A,52.154542,31.225206,B,52.155083,31.225472,300.0,A,NaN,159-164,298.900,NaN,298.9000,63.788622,55.111378
45,perseus,Per-emb-36,A,52.239042,31.237719,B,52.239042,31.237808,300.0,both,NaN,162-167,NaN,64.460,64.4600,0.000000,64.460000
46,perseus,Per-emb-44,A,52.265667,31.267725,B,52.265583,31.267722,300.0,both,NaN,169-175,NaN,342.975,342.9750,268.090848,74.884152

In [4]:
# This loops through each source field with an angle measurement and creates
# a figure with the separation vector and outflow vector overlayed
for i, field in df.groupby('field').agg('first').reset_index().iterrows():

    # verify output path exists and
    # skip already existing files if you don't want to overwrite them
    output_folder = "../results/multi-outflow_plots-2"
    target_name = field['field']
    filename = f"{target_name}_outflow.pdf"
    output_path = os.path.join(output_folder, filename)

    # verify output path exists and
    if not os.path.exists(output_folder):
        os.mkdir(output_folder)

    # open image
    image_filename = (glob.glob(f'/Volumes/Alpha/Research/data/{target_name.casefold()}/*12co*.fits') + glob.glob(f'/Volumes/Alpha/Research/data/{target_name.casefold()}/*spw39*.fits'))[0]
    hdulist = fits.open(image_filename)
    hdu = hdulist[0]

    # set center and size of cutout
    center = SkyCoord(hdu.header['OBSRA'], hdu.header['OBSDEC'], unit=u.degree)
    size = np.array([39, 39]) * u.arcsecond
    distance = field['distance']

    # create figure
    channels = getIdx([field['red_channels'], field['blue_channels']])
    fig = create_m0_map(hdu, center, size, channels, 3, distance)
    fig.set_title(f"{target_name} 12CO M0")

    # add a marker at each source with legend
    target_info = source_info.loc[target_name.casefold()]
    mark_sources(fig, target_info)

    # plot binary separation angle
    center_origin = np.array([np.mean([field['source_a_ra'], field['source_b_ra']]), np.mean([field['source_a_dec'], field['source_b_dec']])])
    separation_angle_north = field['binary_PA']
    # draw separation vector in both directions
    plot_vector(fig, center_origin, separation_angle_north, color='white', length=0.005)
    plot_vector(fig, center_origin, separation_angle_north + 180, color='white', length=0.005)
    
    # plot each outflow vector
    for j, source in df[df['field'] == target_name].reset_index(drop=True).iterrows():
        # define vector origin at the outflow source
        if source['outflow_source'] == 'both':
            outflow_origin = center_origin
        elif source['outflow_source'] == source['source_a']:
            outflow_origin = np.array([source['source_a_ra'], source['source_a_dec']])
        else:
            outflow_origin = np.array([source['source_b_ra'], source['source_b_dec']])

        # plot outflow vector
        outflow_angle_north = source['outflow_PA']
        plot_vector(fig, outflow_origin, outflow_angle_north, color='red', length=0.005)

        # plot component outflow vectors
        if ~pd.isna(source['red_outflow_PA']):
            plot_dotted_vector(fig, outflow_origin, 180 + source['red_outflow_PA'], color='white', length=0.005)
        if ~pd.isna(source['blue_outflow_PA']):
            plot_dotted_vector(fig, outflow_origin, source['blue_outflow_PA'], color='white', length=0.005)
        
        # calculate delta_PA
        angle = np.abs(outflow_angle_north - separation_angle_north) % 180
        angle = np.min([angle, 180 - angle])
            
        # display angle between outflow and separation in top left corner
        source_label = source['outflow_source']
        if source_label == 'both':
            source_label = source['source_a']+'+'+source['source_b']
        fig.ax.text(30,fig.ax.get_xlim()[1]-50-40*(j), f"{source_label} : {np.abs(angle):.2f}°")

    fig.savefig(output_path)

INFO: Auto-setting vmin to  0.000e+00 [aplpy.core]
INFO: Auto-setting vmax to  2.852e-01 [aplpy.core]
INFO: Auto-setting resolution to 199.101 dpi [aplpy.core]
INFO: Auto-setting vmin to  0.000e+00 [aplpy.core]
INFO: Auto-setting vmax to  1.512e-01 [aplpy.core]
INFO: Auto-setting resolution to 282.697 dpi [aplpy.core]
INFO: Auto-setting vmin to  0.000e+00 [aplpy.core]
INFO: Auto-setting vmax to  2.710e-01 [aplpy.core]
INFO: Auto-setting resolution to 300 dpi [aplpy.core]
INFO: Auto-setting vmin to  0.000e+00 [aplpy.core]
INFO: Auto-setting vmax to  9.319e-03 [aplpy.core]
INFO: Auto-setting resolution to 282.697 dpi [aplpy.core]
INFO: Auto-setting vmin to  0.000e+00 [aplpy.core]
INFO: Auto-setting vmax to  2.025e-01 [aplpy.core]
INFO: Auto-setting resolution to 300 dpi [aplpy.core]
INFO: Auto-setting vmin to  0.000e+00 [aplpy.core]
INFO: Auto-setting vmax to  1.667e-02 [aplpy.core]
INFO: Auto-setting resolution to 292.135 dpi [aplpy.core]
INFO: Auto-setting vmin to  0.000e+00 [aplpy.core]
INFO: Auto-setting vmax to  5.521e-02 [aplpy.core]
INFO: Auto-setting resolution to 282.697 dpi [aplpy.core]
INFO: Auto-setting vmin to  0.000e+00 [aplpy.core]
INFO: Auto-setting vmax to  2.207e-02 [aplpy.core]
INFO: Auto-setting resolution to 213.708 dpi [aplpy.core]
INFO: Auto-setting vmin to  0.000e+00 [aplpy.core]
INFO: Auto-setting vmax to  1.245e-01 [aplpy.core]
INFO: Auto-setting resolution to 273.933 dpi [aplpy.core]
INFO: Auto-setting vmin to  0.000e+00 [aplpy.core]
INFO: Auto-setting vmax to  1.827e-02 [aplpy.core]
INFO: Auto-setting resolution to 292.135 dpi [aplpy.core]
INFO: Auto-setting vmin to  0.000e+00 [aplpy.core]
INFO: Auto-setting vmax to  1.456e-01 [aplpy.core]
INFO: Auto-setting resolution to 282.697 dpi [aplpy.core]
INFO: Auto-setting vmin to  0.000e+00 [aplpy.core]
INFO: Auto-setting vmax to  1.101e-01 [aplpy.core]
INFO: Auto-setting resolution to 292.135 dpi [aplpy.core]
INFO: Auto-setting vmin to  0.000e+00 [aplpy.core]
INFO: Auto-setting vmax to  1.305e-01 [aplpy.core]
INFO: Auto-setting resolution to 199.101 dpi [aplpy.core]
INFO: Auto-setting vmin to  0.000e+00 [aplpy.core]
INFO: Auto-setting vmax to  5.401e-02 [aplpy.core]
INFO: Auto-setting resolution to 199.101 dpi [aplpy.core]
INFO: Auto-setting vmin to  0.000e+00 [aplpy.core]
INFO: Auto-setting vmax to  4.388e-02 [aplpy.core]
INFO: Auto-setting resolution to 300 dpi [aplpy.core]
INFO: Auto-setting vmin to  0.000e+00 [aplpy.core]
INFO: Auto-setting vmax to  2.500e-01 [aplpy.core]
INFO: Auto-setting resolution to 194.831 dpi [aplpy.core]
INFO: Auto-setting vmin to  0.000e+00 [aplpy.core]
INFO: Auto-setting vmax to  3.231e-01 [aplpy.core]
INFO: Auto-setting resolution to 194.831 dpi [aplpy.core]
INFO: Auto-setting vmin to  0.000e+00 [aplpy.core]
INFO: Auto-setting vmax to  6.967e-02 [aplpy.core]
INFO: Auto-setting resolution to 194.831 dpi [aplpy.core]
INFO: Auto-setting vmin to  0.000e+00 [aplpy.core]
INFO: Auto-setting vmax to  5.718e-02 [aplpy.core]
INFO: Auto-setting resolution to 243.371 dpi [aplpy.core]
INFO: Auto-setting vmin to  0.000e+00 [aplpy.core]
INFO: Auto-setting vmax to  2.332e-01 [aplpy.core]
INFO: Auto-setting resolution to 199.101 dpi [aplpy.core]
INFO: Auto-setting vmin to  0.000e+00 [aplpy.core]
INFO: Auto-setting vmax to  3.279e-01 [aplpy.core]
INFO: Auto-setting resolution to 186.517 dpi [aplpy.core]
INFO: Auto-setting vmin to  0.000e+00 [aplpy.core]
INFO: Auto-setting vmax to  5.641e-02 [aplpy.core]
INFO: Auto-setting resolution to 292.135 dpi [aplpy.core]
INFO: Auto-setting vmin to  0.000e+00 [aplpy.core]
INFO: Auto-setting vmax to  2.484e-01 [aplpy.core]
INFO: Auto-setting resolution to 194.831 dpi [aplpy.core]
INFO: Auto-setting vmin to  0.000e+00 [aplpy.core]
INFO: Auto-setting vmax to  6.341e-02 [aplpy.core]
INFO: Auto-setting resolution to 282.697 dpi [aplpy.core]
INFO: Auto-setting vmin to  0.000e+00 [aplpy.core]
INFO: Auto-setting vmax to  9.041e-02 [aplpy.core]
INFO: Auto-setting resolution to 282.697 dpi [aplpy.core]
INFO: Auto-setting vmin to  0.000e+00 [aplpy.core]
INFO: Auto-setting vmax to  2.150e-01 [aplpy.core]
INFO: Auto-setting resolution to 282.697 dpi [aplpy.core]
INFO: Auto-setting vmin to  0.000e+00 [aplpy.core]
INFO: Auto-setting vmax to  7.567e-01 [aplpy.core]
INFO: Auto-setting resolution to 203.82 dpi [aplpy.core]
INFO: Auto-setting vmin to  0.000e+00 [aplpy.core]
INFO: Auto-setting vmax to  2.869e-01 [aplpy.core]
INFO: Auto-setting resolution to 213.708 dpi [aplpy.core]
INFO: Auto-setting vmin to  0.000e+00 [aplpy.core]
INFO: Auto-setting vmax to  2.358e-01 [aplpy.core]
INFO: Auto-setting resolution to 208.764 dpi [aplpy.core]
INFO: Auto-setting vmin to  0.000e+00 [aplpy.core]
INFO: Auto-setting vmax to  1.719e-01 [aplpy.core]
INFO: Auto-setting resolution to 224.719 dpi [aplpy.core]
INFO: Auto-setting vmin to  0.000e+00 [aplpy.core]
INFO: Auto-setting vmax to  4.868e-01 [aplpy.core]
INFO: Auto-setting resolution to 219.101 dpi [aplpy.core]
INFO: Auto-setting vmin to  0.000e+00 [aplpy.core]
INFO: Auto-setting vmax to  3.665e-01 [aplpy.core]
INFO: Auto-setting resolution to 208.764 dpi [aplpy.core]
INFO: Auto-setting vmin to  0.000e+00 [aplpy.core]
INFO: Auto-setting vmax to  7.034e-01 [aplpy.core]
INFO: Auto-setting resolution to 219.101 dpi [aplpy.core]
INFO: Auto-setting vmin to  0.000e+00 [aplpy.core]
INFO: Auto-setting vmax to  1.482e-01 [aplpy.core]
INFO: Auto-setting resolution to 203.82 dpi [aplpy.core]
INFO: Auto-setting vmin to  0.000e+00 [aplpy.core]
INFO: Auto-setting vmax to  1.695e-01 [aplpy.core]
INFO: Auto-setting resolution to 203.82 dpi [aplpy.core]
INFO: Auto-setting vmin to  0.000e+00 [aplpy.core]
INFO: Auto-setting vmax to  3.524e-01 [aplpy.core]
INFO: Auto-setting resolution to 208.764 dpi [aplpy.core]
INFO: Auto-setting vmin to  0.000e+00 [aplpy.core]
INFO: Auto-setting vmax to  2.351e-01 [aplpy.core]
INFO: Auto-setting resolution to 213.708 dpi [aplpy.core]

In [5]:
df[df['field'] == target_name]

,group,field,source_a,source_a_ra,source_a_dec,source_b,source_b_ra,source_b_dec,distance,outflow_source,red_channels,blue_channels,red_outflow_PA,blue_outflow_PA,outflow_PA,binary_PA,delta_PA
32,perseus,Per-emb-5,A,52.837258,30.758386,B,52.837258,30.758386,300.0,both,141-148,164-173,297.655,298.945,298.3,90.0,28.3

In [6]:
source_info

,Source,RA,Dec,Dis,LBol,TBol,Class,SigmaYSO,group
Main,,,,,,,,,
hh270vla1,HH270VLA1-A,87.894113,2.946114,430.1,7.34,32.0,0,2.2,orion
hh270vla1,HH270VLA1-B,87.894167,2.946078,430.1,7.34,32.0,0,2.2,orion
hops-12,HOPS-12-A,83.785962,-5.931844,388.6,6.26,42.0,0,49.8,orion
hops-12,HOPS-12-B-A,83.787271,-5.931953,388.6,6.26,42.0,0,49.8,orion
hops-12,HOPS-12-B-B,83.787312,-5.931911,388.6,6.26,42.0,0,49.8,orion
...,...,...,...,...,...,...,...,...,...
per-emb-36,Per-emb-36-B,52.239042,31.237808,300.0,NaN,NaN,NaN,NaN,perseus
per-emb-44,Per-emb-44-A,52.265667,31.267725,300.0,NaN,NaN,NaN,NaN,perseus
per-emb-44,Per-emb-44-B,52.265583,31.267722,300.0,NaN,NaN,NaN,NaN,perseus
per-emb-5,Per-emb-5-A,52.837258,30.758386,300.0,NaN,NaN,NaN,NaN,perseus
per-emb-5,Per-emb-5-B,52.837258,30.758386,300.0,NaN,NaN,NaN,NaN,perseus