In [50]:
import astropy.io.fits as fits
import astropy.units as u
from astropy.nddata import Cutout2D
from astropy.coordinates import SkyCoord
import matplotlib.pyplot as plt
import matplotlib.lines as mlines
import numpy as np
import aplpy
import pandas as pd
from scipy.ndimage import rotate
from astropy.wcs import WCS
from astropy.constants import c
from matplotlib.backends.backend_pdf import PdfPages
import os
import glob
import yaml

import warnings
warnings.filterwarnings("ignore")

In [51]:
with open("../config.yaml", "r") as f:
    config = yaml.safe_load(f)
IMAGE_DIRECTORY = config["data_dir"]
cont_files = glob.glob(f'{IMAGE_DIRECTORY}/*/*cont*.fits')
spw39_files = glob.glob(f'{IMAGE_DIRECTORY}/*/*12co*.fits') + glob.glob(f'{IMAGE_DIRECTORY}/*/*spw39*.fits')

In [52]:
data = []
for cont_file, spw39_file in zip(cont_files, spw39_files):
    cont = fits.open(cont_file)[0]
    spw39 = fits.open(spw39_file)[0]

    cont_bmaj = cont.header['BMAJ'] * 3600
    cont_bmin = cont.header['BMIN'] * 3600
    cont_rms = np.nanstd(cont.data[0,0,:,:])
    cont_length = cont.shape[2]
    cont_width = cont.shape[3]
    cont_xpixscale = np.abs(cont.header['CDELT1'] * 3600)
    cont_ypixscale = np.abs(cont.header['CDELT2'] * 3600)

    spw39_bmaj = spw39.header['BMAJ'] * 3600
    spw39_bmin = spw39.header['BMIN'] * 3600
    spw39_rms = np.nanstd(spw39.data[0,0,:,:])
    spw39_length = spw39.shape[2]
    spw39_width = spw39.shape[3]
    spw39_xpixscale = np.abs(spw39.header['CDELT1'] * 3600)
    spw39_ypixscale = np.abs(spw39.header['CDELT2'] * 3600)

    record = {'name': cont_file, 'cont_bmaj': cont_bmaj, 'cont_bmin': cont_bmin, 'cont_rms': cont_rms, 'cont_length': cont_length, 'cont_width': cont_width, 'cont_xpixscale': cont_xpixscale, 'cont_ypixscale': cont_ypixscale,
              'spw39_bmaj': spw39_bmaj, 'spw39_bmin': spw39_bmin, 'spw39_rms': spw39_rms, 'spw39_length': spw39_length, 'spw39_width': spw39_width, 'spw39_xpixscale': spw39_xpixscale, 'spw39_ypixscale': spw39_ypixscale}
    data.append(record)
df = pd.DataFrame(data)

In [53]:
df

,name,cont_bmaj,cont_bmin,cont_rms,cont_length,cont_width,cont_xpixscale,cont_ypixscale,spw39_bmaj,spw39_bmin,spw39_rms,spw39_length,spw39_width,spw39_xpixscale,spw39_ypixscale
0,/Volumes/Alpha/Research/data/hops-12/cont.fits,0.210106,0.146341,0.000133,1280,1280,0.035,0.035,0.218180,0.154732,0.002444,1372,1372,0.031,0.031
1,/Volumes/Alpha/Research/data/hops-138/cont.fits,0.179100,0.128759,0.000046,1280,1280,0.035,0.035,0.268478,0.179522,0.001719,1176,1176,0.036,0.036
2,/Volumes/Alpha/Research/data/hops-158/cont.fits,0.206553,0.144613,0.000038,1280,1280,0.035,0.035,0.212107,0.154954,0.002090,1372,1372,0.031,0.031
3,/Volumes/Alpha/Research/data/hops-163/cont.fits,0.194929,0.142247,0.000052,1280,1280,0.035,0.035,0.203847,0.151492,0.002446,1440,1440,0.030,0.030
4,/Volumes/Alpha/Research/data/hops-168/cont.fits,0.206340,0.147036,0.000217,1280,1280,0.035,0.035,0.186402,0.135598,0.002683,1620,1620,0.026,0.026
5,/Volumes/Alpha/Research/data/hops-173/cont.fits,0.203953,0.142428,0.000080,1280,1280,0.035,0.035,0.210531,0.152858,0.002473,1372,1372,0.031,0.031
6,/Volumes/Alpha/Research/data/hops-182/cont.fits,0.203743,0.145513,0.000703,1280,1280,0.035,0.035,0.186554,0.134891,0.003030,1620,1620,0.026,0.026
7,/Volumes/Alpha/Research/data/hops-193/cont.fits,0.197948,0.140993,0.000043,1280,1280,0.035,0.035,0.206461,0.150705,0.002336,1440,1440,0.030,0.030
8,/Volumes/Alpha/Research/data/hops-203/cont.fits,0.210765,0.148905,0.000164,1280,1280,0.035,0.035,0.218308,0.157367,0.002217,1372,1372,0.031,0.031
9,/Volumes/Alpha/Research/data/hops-213/cont.fits,0.246690,0.177168,0.000111,1280,1280,0.035,0.035,0.311179,0.247948,0.001334,1050,1050,0.041,0.041
10,/Volumes/Alpha/Research/data/hops-242/cont.fits,0.198672,0.143920,0.000040,1280,1280,0.035,0.035,0.206570,0.153644,0.002259,1372,1372,0.031,0.031
11,/Volumes/Alpha/Research/data/hops-248/cont.fits,0.204999,0.143628,0.000081,1280,1280,0.035,0.035,0.211375,0.153635,0.002151,1372,1372,0.031,0.031
12,/Volumes/Alpha/Research/data/hops-255/cont.fits,0.206461,0.141024,0.000054,1280,1280,0.035,0.035,0.214178,0.150483,0.002246,1440,1440,0.030,0.030
13,/Volumes/Alpha/Research/data/hops-261/cont.fits,0.177651,0.128364,0.000044,1280,1280,0.035,0.035,0.260009,0.149553,0.001432,1512,1512,0.028,0.028
14,/Volumes/Alpha/Research/data/hops-28/cont.fits,0.226704,0.162683,0.000037,1280,1280,0.035,0.035,0.228913,0.168577,0.002044,1250,1250,0.034,0.034
15,/Volumes/Alpha/Research/data/hops-281/cont.fits,0.205156,0.147209,0.000102,1280,1280,0.035,0.035,0.212089,0.157431,0.002110,1344,1344,0.032,0.032
16,/Volumes/Alpha/Research/data/hops-282/cont.fits,0.198943,0.141451,0.000043,1280,1280,0.035,0.035,0.209501,0.150962,0.002170,1440,1440,0.030,0.030
17,/Volumes/Alpha/Research/data/hops-288/cont.fits,0.198183,0.145720,0.000606,1280,1280,0.035,0.035,0.205696,0.154425,0.002130,1372,1372,0.031,0.031
18,/Volumes/Alpha/Research/data/hops-290/cont.fits,0.194309,0.140596,0.000069,1280,1280,0.035,0.035,0.203860,0.150421,0.002128,1440,1440,0.030,0.030
19,/Volumes/Alpha/Research/data/hops-32/cont.fits,0.196200,0.137381,0.000053,1280,1280,0.035,0.035,0.206469,0.146569,0.002306,1458,1458,0.029,0.029
20,/Volumes/Alpha/Research/data/hops-395/cont.fits,0.193784,0.140836,0.000182,1280,1280,0.035,0.035,0.202728,0.150608,0.002090,1440,1440,0.030,0.030
21,/Volumes/Alpha/Research/data/hops-45/cont.fits,0.206373,0.144334,0.000080,1280,1280,0.035,0.035,0.215392,0.153850,0.002149,1372,1372,0.031,0.031
22,/Volumes/Alpha/Research/data/hops-56/cont.fits,0.201286,0.140392,0.000071,1280,1280,0.035,0.035,0.209608,0.149249,0.002141,1440,1440,0.030,0.030
23,/Volumes/Alpha/Research/data/hops-70/cont.fits,0.204741,0.146494,0.000070,1280,1280,0.035,0.035,0.210915,0.155940,0.002169,1372,1372,0.031,0.031
24,/Volumes/Alpha/Research/data/hops-75/cont.fits,0.202992,0.142653,0.000047,1280,1280,0.035,0.035,0.209401,0.152566,0.002214,1372,1372,0.031,0.031
25,/Volumes/Alpha/Research/data/hops-77/cont.fits,0.201939,0.143032,0.000046,1280,1280,0.035,0.035,0.207905,0.153109,0.002232,1372,1372,0.031,0.031
26,/Volumes/Alpha/Research/data/hops-84/cont.fits,0.206541,0.143569,0.000430,1280,1280,0.035,0.035,0.212529,0.153793,0.002159,1372,1372,0.031,0.031
27,/Volumes/Alpha/Research/data/hops-85/cont.fits,0.204717,0.141605,0.000090,1280,1280,0.035,0.035,0.212651,0.150381,0.002176,1440,1440,0.030,0.030
28,/Volumes/Alpha/Research/data/hops-92/cont.fits,0.211671,0.145409,0.000261,1280,1280,0.035,0.035,0.218512,0.154119,0.002165,1372,1372,0.031,0.031
29,/Volumes/Alpha/Research/data/hh270vla1/cont.fits,0.248620,0.227510,0.000078,1280,1280,0.035,0.035,0.250203,0.226159,0.001786,960,960,0.044,0.044
30,/Volumes/Alpha/Research/data/hops-304/cont.fits,0.254047,0.222822,0.000073,1280,1280,0.035,0.035,0.251822,0.221361,0.001655,960,960,0.044,0.044
31,/Volumes/Alpha/Research/data/hops-312/cont.fits,0.255465,0.224350,0.000069,1280,1280,0.035,0.035,0.254808,0.225835,0.001596,960,960,0.044,0.044
32,/Volumes/Alpha/Research/data/hops-323/cont.fits,0.262607,0.231222,0.000171,1280,1280,0.035,0.035,0.261985,0.227322,0.001678,960,960,0.045,0.045
33,/Volumes/Alpha/Research/data/hops-357/cont.fits,0.249227,0.222191,0.000302,1280,1280,0.035,0.035,0.250958,0.220931,0.001614,960,960,0.044,0.044
34,/Volumes/Alpha/Research/data/hops-361-n/cont.fits,0.258593,0.224658,0.001444,1280,1280,0.035,0.035,0.264800,0.226514,0.001699,960,960,0.045,0.045
35,/Volumes/Alpha/Research/data/hops-363/cont.fits,0.261520,0.230359,0.000073,1280,1280,0.035,0.035,0.262603,0.227323,0.001710,960,960,0.045,0.045
36,/Volumes/Alpha/Research/data/hops-364/cont.fits,0.257011,0.226300,0.000240,1280,1280,0.035,0.035,0.226704,0.180902,0.001866,1176,1176,0.036,0.036
37,/Volumes/Alpha/Research/data/hops-366/cont.fits,0.259544,0.231135,0.000140,1280,1280,0.035,0.035,0.256902,0.226894,0.001728,960,960,0.044,0.044
38,/Volumes/Alpha/Research/data/hops-384/cont.fits,0.237417,0.201501,0.000461,1280,1280,0.035,0.035,0.273112,0.243903,0.001618,896,896,0.047,0.047
39,/Volumes/Alpha/Research/data/hops-400/cont.fits,0.257101,0.228304,0.000893,1280,1280,0.035,0.035,0.252102,0.225253,0.001564,960,960,0.045,0.045
40,/Volumes/Alpha/Research/data/per-emb-2/oussid....,0.226597,0.151959,0.000441,1440,1440,0.031,0.031,0.283534,0.198937,0.003993,1080,1080,0.039,0.039
41,/Volumes/Alpha/Research/data/per-emb-12/oussid...,0.233729,0.167531,0.001904,1344,1344,0.034,0.034,0.293845,0.223018,0.003530,980,980,0.043,0.043
42,/Volumes/Alpha/Research/data/per-emb-17/oussid...,0.226144,0.156619,0.000134,1400,1400,0.032,0.032,0.284839,0.209916,0.004190,1024,1024,0.041,0.041
43,/Volumes/Alpha/Research/data/per-emb-18/oussid...,0.230844,0.160987,0.000249,1344,1344,0.033,0.033,0.292432,0.216419,0.003575,1000,1000,0.042,0.042
44,/Volumes/Alpha/Research/data/per-emb-22/oussid...,0.231220,0.152931,0.000133,1440,1440,0.031,0.031,0.291787,0.200574,0.003945,1050,1050,0.040,0.040
45,/Volumes/Alpha/Research/data/per-emb-27/oussid...,0.234270,0.163030,0.000510,1344,1344,0.033,0.033,0.291737,0.215278,0.003595,1000,1000,0.042,0.042
46,/Volumes/Alpha/Research/data/per-emb-33/oussid...,0.231829,0.154795,0.000555,1440,1440,0.031,0.031,0.290912,0.203641,0.003843,1050,1050,0.040,0.040
47,/Volumes/Alpha/Research/data/per-emb-35/oussid...,0.237323,0.165197,0.000123,1344,1344,0.033,0.033,0.301244,0.222567,0.003510,980,980,0.043,0.043
48,/Volumes/Alpha/Research/data/per-emb-36/oussid...,0.235049,0.162429,0.000404,1344,1344,0.033,0.033,0.294065,0.218561,0.003426,980,980,0.043,0.043
49,/Volumes/Alpha/Research/data/per-emb-44/oussid...,0.235496,0.161734,0.000588,1400,1400,0.032,0.032,0.292836,0.214025,0.004008,1000,1000,0.042,0.042
50,/Volumes/Alpha/Research/data/per-emb-107/uid__...,0.281396,0.197759,0.000420,1152,1152,0.039,0.039,0.294499,0.213637,0.010922,1024,1024,0.041,0.041

In [54]:
df_orion = df[~df['name'].str.contains('per')]
df_perseus = df[df['name'].str.contains('per')]

In [55]:
df_orion.describe()

,cont_bmaj,cont_bmin,cont_rms,cont_length,cont_width,cont_xpixscale,cont_ypixscale,spw39_bmaj,spw39_bmin,spw39_rms,spw39_length,spw39_width,spw39_xpixscale,spw39_ypixscale
count,40.000000,40.000000,40.000000,40.0,40.0,40.000,40.000,40.000000,40.000000,40.000000,40.000000,40.000000,40.000000,40.000000
mean,0.217565,0.166366,0.000198,1280.0,1280.0,0.035,0.035,0.227159,0.174544,0.002044,1277.450000,1277.450000,0.034450,0.034450
std,0.025666,0.037280,0.000281,0.0,0.0,0.000,0.000,0.027768,0.035195,0.000353,213.629436,213.629436,0.006484,0.006484
min,0.177651,0.128364,0.000037,1280.0,1280.0,0.035,0.035,0.186402,0.134891,0.001334,896.000000,896.000000,0.026000,0.026000
25%,0.200700,0.142087,0.000053,1280.0,1280.0,0.035,0.035,0.209027,0.150898,0.001716,1027.500000,1027.500000,0.030000,0.030000
50%,0.206357,0.145461,0.000080,1280.0,1280.0,0.035,0.035,0.213415,0.154272,0.002135,1372.000000,1372.000000,0.031000,0.031000
75%,0.247173,0.206673,0.000191,1280.0,1280.0,0.035,0.035,0.251892,0.221038,0.002220,1440.000000,1440.000000,0.041750,0.041750
max,0.262607,0.231222,0.001444,1280.0,1280.0,0.035,0.035,0.311179,0.247948,0.003030,1620.000000,1620.000000,0.047000,0.047000

In [58]:
df_perseus = df_perseus[~df_perseus['name'].str.contains('107')]
df_perseus.describe()

,cont_bmaj,cont_bmin,cont_rms,cont_length,cont_width,cont_xpixscale,cont_ypixscale,spw39_bmaj,spw39_bmin,spw39_rms,spw39_length,spw39_width,spw39_xpixscale,spw39_ypixscale
count,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000
mean,0.232250,0.159721,0.000504,1384.000000,1384.000000,0.032300,0.032300,0.291723,0.212294,0.003761,1014.400000,1014.400000,0.041500,0.041500
std,0.003694,0.005325,0.000524,44.621868,44.621868,0.001059,0.001059,0.004916,0.008724,0.000265,35.122642,35.122642,0.001434,0.001434
min,0.226144,0.151959,0.000123,1344.000000,1344.000000,0.031000,0.031000,0.283534,0.198937,0.003426,980.000000,980.000000,0.039000,0.039000
25%,0.230938,0.155251,0.000163,1344.000000,1344.000000,0.031250,0.031250,0.291118,0.205210,0.003541,985.000000,985.000000,0.040250,0.040250
50%,0.232779,0.161361,0.000423,1372.000000,1372.000000,0.032500,0.032500,0.292109,0.214651,0.003719,1000.000000,1000.000000,0.042000,0.042000
75%,0.234855,0.162880,0.000544,1430.000000,1430.000000,0.033000,0.033000,0.293593,0.218026,0.003981,1043.500000,1043.500000,0.042750,0.042750
max,0.237323,0.167531,0.001904,1440.000000,1440.000000,0.034000,0.034000,0.301244,0.223018,0.004190,1080.000000,1080.000000,0.043000,0.043000