In [2]:
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
df = pd.read_csv('../data/output/separations.csv')
df

          pair  tertiary  separation class
0    HH270VLA1     False        99.4    C0
1      HOPS-12      True      1853.5    C0
2      HOPS-12     False        80.6    C0
3     HOPS-168     False        73.7    C0
4     HOPS-173     False       103.0    C0
5     HOPS-182     False       381.5    C0
6     HOPS-193     False       100.0    C1
7     HOPS-203     False        49.7    C0
8     HOPS-203      True      1085.5    C0
9     HOPS-213     False       114.4    FS
10    HOPS-281     False       311.6    FS
11    HOPS-282     False        70.1    C1
12    HOPS-288      True       221.9    C0
13    HOPS-288     False        61.3    C0
14    HOPS-290     False       332.7    C0
15    HOPS-304     False       272.7    FS
16    HOPS-312     False       134.7    C0
17     HOPS-32     False       162.2    C0
18    HOPS-323     False       273.6    C1
19  HOPS-361-N     False        37.6    C0
20    HOPS-363     False        79.5    FS
21    HOPS-364     False        65.5    C1
22    HOPS-366     False        61.1    C1
23    HOPS-384     False        49.0    C0
24    HOPS-395     False        65.4    C0
25    HOPS-400     False       184.0    C0
26     HOPS-75     False        99.8    C0
27     HOPS-84     False       275.5    C1
28     HOPS-92     False       108.4    FS
29     HOPS-92      True       498.8    FS
30  Per-emb-12     False       549.0    C0
31  Per-emb-17     False        83.4    C0
32  Per-emb-18     False        25.5    C0
33   Per-emb-2     False        24.1    C0
34  Per-emb-22     False       225.4    C0
35  Per-emb-27     False       186.0    C0
36  Per-emb-33      True       263.2    C0
37  Per-emb-33     False        79.6    C0
38  Per-emb-35     False       572.5    C1
39  Per-emb-36     False        93.3    C1
40  Per-emb-44     False        90.1    C0

In [7]:
df[df['tertiary'] == False].describe()

       separation
count   36.000000
mean   154.886111
std    136.258677
min     24.100000
25%     68.950000
50%     99.600000
75%    195.850000
max    572.500000

Among the 36 fields with measured outflow PAs, the maximum binary separation is 572.5 AU, the minimum is 24.1 AU, and the median is 99.6 AU.