In [5]:
import numpy as np
import astropy.io.ascii
import pandas as pd

This notebook looks at the data for the sources.

In [6]:
targets = [
    "HH270VLA1",
    "HOPS-323",
    "HOPS-312",
    "HOPS-364",
    # HOPS-361-N??
    "HOPS-361",
    "HOPS-366",
    "HOPS-384",
    "HOPS-304",
    "HOPS-357",
    "HOPS-363",
    "HOPS-400",
    "HOPS-290",
    "HOPS-56",
    "HOPS-193",
    "HOPS-242",
    "HOPS-70",
    "HOPS-138",
    "HOPS-85",
    "HOPS-182",
    "HOPS-28",
    "HOPS-92",
    "HOPS-32",
    "HOPS-158",
    "HOPS-75",
    "HOPS-395",
    "HOPS-43",
    "HOPS-255",
    "HOPS-213",
    "HOPS-77",
    "HOPS-281",
    "HOPS-173",
    "HOPS-282",
    "HOPS-84",
    "HOPS-288",
    "HOPS-248",
    "HOPS-168",
    "HOPS-203",
    "HOPS-163",
    "HOPS-12",
    "HOPS-261"
]

In [7]:
df = astropy.io.ascii.read("../data/distances.txt").to_pandas()
df[df['Main'] == 'HOPS-384']

,Source,Main,RAh,RAm,RAs,DE-,DEd,DEm,DEs,LBol,TBol,Class,SigmaYSO,Dis
96,HOPS-384-region-H,HOPS-384,5,41,45.902,-,1,54,11.17,1404.97,51.9,0,1185.4,409.5
99,NGC2024-FIR3-B,HOPS-384,5,41,43.167,-,1,54,25.42,209.14,-99.0,0,1185.4,409.5
100,NGC2024-FIR3-A,HOPS-384,5,41,43.087,-,1,54,26.27,209.14,-99.0,0,1039.4,409.5
101,HOPS-384-region-D,HOPS-384,5,41,45.524,-,1,54,27.14,1404.97,51.9,0,1185.4,409.5
105,HOPS-384-region-G,HOPS-384,5,41,43.915,-,1,54,34.09,1404.97,51.9,0,1039.4,409.5
108,HOPS-384-B,HOPS-384,5,41,44.016,-,1,54,43.14,1404.97,51.9,0,527.0,409.5
110,HOPS-384-A-B,HOPS-384,5,41,44.140,-,1,54,45.97,1404.97,51.9,0,527.0,409.5
111,HOPS-384-A,HOPS-384,5,41,44.135,-,1,54,46.06,1404.97,51.9,0,527.0,409.5
113,HOPS-384-C,HOPS-384,5,41,44.252,-,1,54,55.53,1404.97,51.9,0,527.0,409.5
114,HOPS-384-region-E,HOPS-384,5,41,45.735,-,1,54,57.97,1404.97,51.9,0,386.4,409.5

In [8]:
df[df['Main'] == 'HOPS-12']

,Source,Main,RAh,RAm,RAs,DE-,DEd,DEm,DEs,LBol,TBol,Class,SigmaYSO,Dis
250,HOPS-12-A,HOPS-12,5,35,8.631,-,5,55,54.64,6.26,42.0,0,49.8,388.6
251,HOPS-12-B-B,HOPS-12,5,35,8.955,-,5,55,54.88,6.26,42.0,0,49.8,388.6
252,HOPS-12-B-A,HOPS-12,5,35,8.945,-,5,55,55.03,6.26,42.0,0,49.8,388.6

In [ ]:
df = df[df['Main'].isin(targets)]
df['RA'] = 15 * (df['RAh'] + df['RAm'] / 60 + df['RAs'] / 3600)
df['DE-'] = df["DE-"].apply(lambda x: -1 if x == "-" else 1)
df['Dec'] = df['DE-'] * (df['DEd'] + df['DEm'] / 60 + df['DEs'] / 3600)
df = df[['Main', 'Source', 'RA', 'Dec', 'Dis', 'LBol', 'TBol', 'Class', 'SigmaYSO']]
# df = df.set_index(['Main', 'Source'])
df = df.sort_values(['Main', 'Source']).reset_index(drop=True)
df.to_csv("../data/source_info.csv",index=False)
df

,Main,Source,RA,Dec,Dis,LBol,TBol,Class,SigmaYSO
0,HH270VLA1,HH270VLA1-A,87.894113,2.946114,430.1,7.34,32.0,0,2.2
1,HH270VLA1,HH270VLA1-B,87.894167,2.946078,430.1,7.34,32.0,0,2.2
2,HOPS-12,HOPS-12-A,83.785962,-5.931844,388.6,6.26,42.0,0,49.8
3,HOPS-12,HOPS-12-B-A,83.787271,-5.931953,388.6,6.26,42.0,0,49.8
4,HOPS-12,HOPS-12-B-B,83.787312,-5.931911,388.6,6.26,42.0,0,49.8
...,...,...,...,...,...,...,...,...,...
104,HOPS-85,HOPS-85-A,83.867454,-5.061444,392.8,14.24,174.2,Flat,77.4
105,HOPS-85,HOPS-85-B,83.867471,-5.061469,392.8,14.24,174.2,Flat,77.4
106,HOPS-92,HOPS-92-A-A,83.826404,-5.009150,392.7,17.58,186.3,Flat,139.2
107,HOPS-92,HOPS-92-A-B,83.826367,-5.009217,392.7,17.58,186.3,Flat,139.2
108,HOPS-92,HOPS-92-B,83.826125,-5.009422,392.7,17.58,186.3,Flat,139.2

In [10]:
df[df['Main'] == 'HOPS-384']

,Main,Source,RA,Dec,Dis,LBol,TBol,Class,SigmaYSO
73,HOPS-384,HOPS-384-A,85.433896,-1.912794,409.5,1404.97,51.9,0,527.0
74,HOPS-384,HOPS-384-A-B,85.433917,-1.912769,409.5,1404.97,51.9,0,527.0
75,HOPS-384,HOPS-384-B,85.433400,-1.911983,409.5,1404.97,51.9,0,527.0
76,HOPS-384,HOPS-384-C,85.434383,-1.915425,409.5,1404.97,51.9,0,527.0
77,HOPS-384,HOPS-384-region-D,85.439683,-1.907539,409.5,1404.97,51.9,0,1185.4
78,HOPS-384,HOPS-384-region-E,85.440562,-1.916103,409.5,1404.97,51.9,0,386.4
79,HOPS-384,HOPS-384-region-G,85.432979,-1.909469,409.5,1404.97,51.9,0,1039.4
80,HOPS-384,HOPS-384-region-H,85.441258,-1.903103,409.5,1404.97,51.9,0,1185.4
81,HOPS-384,NGC2024-FIR3-A,85.429529,-1.907297,409.5,209.14,-99.0,0,1039.4
82,HOPS-384,NGC2024-FIR3-B,85.429862,-1.907061,409.5,209.14,-99.0,0,1185.4

In [11]:
df.groupby("Main").agg('count')

           Source  RA  Dec  Dis  LBol  TBol  Class  SigmaYSO
Main
HH270VLA1       2   2    2    2     2     2      2         2
HOPS-12         3   3    3    3     3     3      3         3
HOPS-138        2   2    2    2     2     2      2         2
HOPS-158        2   2    2    2     2     2      2         2
HOPS-163        2   2    2    2     2     2      2         2
HOPS-168        2   2    2    2     2     2      2         2
HOPS-173        2   2    2    2     2     2      2         2
HOPS-182        3   3    3    3     3     3      3         3
HOPS-193        2   2    2    2     2     2      2         2
HOPS-203        3   3    3    3     3     3      3         3
HOPS-213        2   2    2    2     2     2      2         2
HOPS-242        2   2    2    2     2     2      2         2
HOPS-248        2   2    2    2     2     2      2         2
HOPS-255        2   2    2    2     2     2      2         2
HOPS-261        2   2    2    2     2     2      2         2
HOPS-28         2   2    2    2     2     2      2         2
HOPS-281        2   2    2    2     2     2      2         2
HOPS-282        2   2    2    2     2     2      2         2
HOPS-288        3   3    3    3     3     3      3         3
HOPS-290        2   2    2    2     2     2      2         2
HOPS-304        2   2    2    2     2     2      2         2
HOPS-312        2   2    2    2     2     2      2         2
HOPS-32         2   2    2    2     2     2      2         2
HOPS-323        2   2    2    2     2     2      2         2
HOPS-357        2   2    2    2     2     2      2         2
HOPS-361       13  13   13   13    13    13     13        13
HOPS-363        2   2    2    2     2     2      2         2
HOPS-364        2   2    2    2     2     2      2         2
HOPS-366        2   2    2    2     2     2      2         2
HOPS-384       10  10   10   10    10    10     10        10
HOPS-395        2   2    2    2     2     2      2         2
HOPS-400        2   2    2    2     2     2      2         2
HOPS-43         1   1    1    1     1     1      1         1
HOPS-56         4   4    4    4     4     4      4         4
HOPS-70         5   5    5    5     5     5      5         5
HOPS-75         2   2    2    2     2     2      2         2
HOPS-77         3   3    3    3     3     3      3         3
HOPS-84         2   2    2    2     2     2      2         2
HOPS-85         2   2    2    2     2     2      2         2
HOPS-92         3   3    3    3     3     3      3         3